# Generated by Django 5.0.7 on 2024-07-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'USER'), ('agent', 'Agent')], default=1, max_length=30, verbose_name='User Type'),
            preserve_default=False,
        ),
    ]
