# Generated by Django 5.0.7 on 2024-07-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], max_length=30, verbose_name='User Type'),
        ),
    ]
