# Generated by Django 5.0.7 on 2024-07-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='twitter',
            field=models.CharField(blank=True, default='twitter.com', max_length=50, null=True, verbose_name='Twitter'),
        ),
    ]
