# Generated by Django 5.0.7 on 2024-07-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_facebook_alter_user_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skype',
            field=models.CharField(blank=True, default='https://www.skype.com/', max_length=50, null=True, verbose_name='Skype'),
        ),
    ]
