# Generated by Django 5.0.7 on 2024-08-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_skype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='instagram',
            field=models.CharField(blank=True, default='https://www.instagram.com/', max_length=50, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skype',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Skype'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, default='https://telegram.org/', max_length=50, null=True, verbose_name='Telegram'),
        ),
    ]
