# Generated by Django 5.0.6 on 2025-03-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_instagram_alter_user_skype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='+998935199999', max_length=50, verbose_name='Tel'),
        ),
    ]
