# Generated by Django 5.0.7 on 2024-07-31 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_slug_alter_blog_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='categories',
            new_name='category',
        ),
    ]
