# Generated by Django 5.0.7 on 2024-07-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Qulaylik',
                'verbose_name_plural': 'Qulayliklar ',
                'db_table': 'amenities',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='banner/%Y/%m/%d/', verbose_name='photo')),
            ],
            options={
                'db_table': 'gallery',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('names', models.CharField(max_length=255, verbose_name='Name')),
                ('slugs', models.SlugField(unique=True)),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('card', models.ImageField(upload_to='house/card/', verbose_name='card')),
                ('prices', models.PositiveIntegerField(verbose_name='Price')),
                ('descs', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('New to old', 'new_to_old'), ('For Rent', 'for_rent'), ('For Sale', 'for_sale')], max_length=20, verbose_name='status')),
                ('areas', models.FloatField(default=0)),
                ('beds', models.PositiveIntegerField(default=0)),
                ('baths', models.PositiveIntegerField(default=0)),
                ('garages', models.PositiveIntegerField(default=0)),
                ('videos', models.FileField(null=True, upload_to='video/', verbose_name='video')),
                ('plans', models.ImageField(blank=True, null=True, upload_to='plan/', verbose_name='plan')),
                ('locations', models.TextField(verbose_name='locations')),
            ],
            options={
                'verbose_name': 'Uy',
                'verbose_name_plural': 'Uylar',
                'db_table': 'house',
            },
        ),
        migrations.CreateModel(
            name='HouseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('comment', models.TextField(verbose_name='Comment')),
            ],
            options={
                'db_table': 'house_comment',
            },
        ),
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Uy_turi',
                'verbose_name_plural': 'Uy_turlari',
                'db_table': 'house_type',
            },
        ),
    ]
