# Generated by Django 5.0.7 on 2024-07-19 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('house', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='agents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='houses'),
        ),
        migrations.AddField(
            model_name='house',
            name='amenities',
            field=models.ManyToManyField(to='house.amenities', verbose_name='amenities'),
        ),
        migrations.AddField(
            model_name='house',
            name='galleries',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='house.gallery', verbose_name='gallery'),
        ),
        migrations.AddField(
            model_name='housecomment',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.house', verbose_name='house'),
        ),
        migrations.AddField(
            model_name='house',
            name='house_types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses_type', to='house.housetype', verbose_name='house_type'),
        ),
    ]
