# Generated by Django 5.0.7 on 2024-07-19 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housecomment',
            old_name='comment',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='housecomment',
            old_name='email',
            new_name='emails',
        ),
        migrations.RenameField(
            model_name='housecomment',
            old_name='house',
            new_name='houses',
        ),
        migrations.RenameField(
            model_name='housecomment',
            old_name='name',
            new_name='names',
        ),
        migrations.RemoveField(
            model_name='house',
            name='galleries',
        ),
        migrations.AddField(
            model_name='gallery',
            name='house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='house.house', verbose_name='house'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='housetype',
            name='slug',
            field=models.SlugField(default=1, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
