# Generated by Django 5.0.7 on 2024-07-22 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_rename_comment_housecomment_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='agents',
            new_name='agent',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='amenities',
            new_name='amenity',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='areas',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='baths',
            new_name='bath',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='beds',
            new_name='bed',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='descs',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='garages',
            new_name='garage',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='house_types',
            new_name='house_type',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='locations',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='names',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='plans',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='prices',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='slugs',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='videos',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='housecomment',
            old_name='comments',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='housecomment',
            old_name='emails',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='housecomment',
            old_name='houses',
            new_name='house',
        ),
        migrations.RenameField(
            model_name='housecomment',
            old_name='names',
            new_name='name',
        ),
        migrations.CreateModel(
            name='BannerHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='house.house', verbose_name='house')),
            ],
            options={
                'db_table': 'house_banner',
            },
        ),
    ]
