# Generated by Django 5.0.7 on 2024-07-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_alter_house_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/', verbose_name='video'),
        ),
    ]
