# Generated by Django 5.0.7 on 2024-08-12 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_alter_house_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house', to=settings.AUTH_USER_MODEL, verbose_name='Agent'),
        ),
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('new to old', 'new to old'), ('for_rent', 'for_rent'), ('for_sale', 'for_sale')], max_length=20, verbose_name='status'),
        ),
    ]
