# Generated by Django 5.0.7 on 2024-08-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0009_alter_house_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('new to old', 'new to old'), ('for rent', 'for rent'), ('for sale', 'for sale')], max_length=20, verbose_name='status'),
        ),
    ]
