# Generated by Django 5.0.7 on 2025-03-16 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0010_alter_house_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='bath',
            new_name='room',
        ),
    ]
