# Generated by Django 5.0.7 on 2025-03-16 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0011_rename_bath_house_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='room',
            new_name='bath',
        ),
    ]
