# Generated by Django 5.0.6 on 2025-03-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0014_district_slug_alter_house_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='plan',
            field=models.ImageField(blank=True, default='img/plan2.png', null=True, upload_to='plan/', verbose_name='plan'),
        ),
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('sotilgan', 'sotilgan'), ('ijara uchun', 'ijara uchun'), ('sotuvda', 'sotuvda')], max_length=20, verbose_name='status'),
        ),
    ]
