# Generated by Django 5.0.6 on 2025-03-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0015_alter_house_plan_alter_house_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='plan',
            field=models.ImageField(blank=True, default='plan/plan2.png', null=True, upload_to='plan/', verbose_name='plan'),
        ),
    ]
